### ISSUE TITLE
Split project into monorepo

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#1410]
Converting the Netlify CMS repo to a monorepo managed via Lerna/Yarn Workspaces helps with the following:

1. Maintaining a small core.
2. Providing "official" extensions in their own packages.
3. Easier to copy and modify official extensions for specific use cases.
4. Separate extension packages more accessible as examples.

Planning next steps:
- [x] locate where standalone package targets are depending directly on Netlify CMS internals
- [x] propose changes to centralize or replace internal dependencies
- [ ] determine which API changes are prerequisite to splitting

## Standalone package targets
<details>
<summary>Expand...</summary>

### Backends
**Location:** [`src/backends/`](https://github.com/netlify/netlify-cms/tree/master/src/backends)
**Package prefix:** `netlify-cms-backend`

#### Internal dependencies
- `src/components/UI/Icon`
- `src/constants/publishModes`
- `src/lib/implicit-oauth`
- `src/lib/LocalForage`
- `src/lib/netlify-auth`
- `src/lib/pathHelper`
- `src/lib/promiseHelper`
- `src/lib/unsentRequest`
- `src/valueObjects/AssetProxy`
- `src/valueObjects/Cursor`
- `src/valueObjects/errors/APIError`
- `src/valueObjects/errors/EditorialWorkflowError`
- css var/apply

#### Notes
- Test repo should be split out as well, maybe call it `netlify-cms-backend-memory`

#### Undetermined
- How should styles for backend auth pages be provided?

### Widgets
**Location:** [`src/components/EditorWidgets/`](https://github.com/netlify/netlify-cms/tree/master/src/components/EditorWidgets)
**Package prefix:** `netlify-cms-widget`

#### Internal dependencies
- `src/components/UI/Icon`
- `src/components/UI/ListItemTopBar`
- `src/components/UI/Toggle`
- css var/apply

##### Image/File widgets
- `src/lib/textHelper`

##### Object widget
- `src/components/Editor/EditorControlPane/EditorControl`

##### Relation widget
- `src/actions/search` (`query`, `clearSearch`)
- redux state - `search.isFetching`, `search.queryHits`
- `src/components/UI/Loader`

##### Markdown widget
- `src/components/UI/Dropdown`
- `src/lib/registry` (`resolveWidget`, `getEditorComponents`)
- `src/lib/regexHelper`

#### Tasks
- [ ] combine date/datetime widgets
- [ ] combine file/image widgets

#### Notes
- Combined widgets could be registered under all current names in the full distribution, e.g. combined date widget registered as both `date` and `datetime`. Wondering if some aspects of configuration should be possible at registration, if only to help 2.0 be backwards compatible. Behavior would be deprecated and dropped at 3.0.

#### Undetermined
- How should widgets provide styles?

### Editor Components
**Location:** [`src/components/MarkdownPlugins/`](https://github.com/netlify/netlify-cms/tree/master/src/components/MarkdownPlugins)
**Package prefix:** `netlify-cms-editor-component`

No internal dependencies
</details>

## Dependency Change Proposals
<details>
<summary>Expand...</summary>

### Move to combined `netlify-cms-lib-util` standalone package
- [ ] `src/lib/LocalForage`
- [ ] `src/lib/pathHelper`
- [ ] `src/lib/promiseHelper`
- [ ] `src/lib/regexHelper`
- [ ] `src/lib/textHelper`
- [ ] `src/lib/unsentRequest`

### Move to combined `netlify-cms-lib-auth` standalone package
- [ ] `src/lib/implicit-oauth`
- [ ] `src/lib/netlify-auth`

### Move to combined `netlify-cms-ui-default` standalone package
- [ ] `src/components/UI/Dropdown`
- [ ] `src/components/UI/Icon`
- [ ] `src/components/UI/ListItemTopBar`
- [ ] `src/components/UI/Loader`
- [ ] `src/components/UI/Toggle`

### Replace with third party lib
- [ ] `src/lib/randomGenerator` (used by `src/libs/implicit-oauth`)

### Provide access via Widget API
- [ ] `src/actions/search` (`query`, `clearSearch`)
- [ ] redux state (read) - `search.isFetching`, `search.queryHits`
- [ ] `src/lib/registry` (`resolveWidget`, `getEditorComponents`)

### Provide access via Backend API
- [ ] `src/valueObjects/Cursor`
  Provide `Cursor.create` to backend as `createCursor` via constructor? 
  
### Provide via general info read-only object (no values in this object ever change)
- [ ] `src/constants/publishModes`
  - replace `EDITORIAL_WORKFLOW` via `workflow.enabled` boolean
  - provide `status` via `workflow.statuses` plain array

### Replace via code change
- [ ] `src/valueObjects/AssetProxy`
  Stop checking for `instanceof AssetProxy` and check for `item.toBase64` method to be present
- [ ] `src/routing/history` (used by `src/libs/implicit-oauth`)
  pass a `clearHash` method that runs `history.replace('/')` to backend.authComponent as a prop
- [ ] `src/valueObjects/errors/APIError`
- [ ] `src/valueObjects/errors/EditorialWorkflowError`
  Catch generic errors in `backend.js` and create proper error types from there
- [ ] `src/components/Editor/EditorControlPane/EditorControl` (used by Object widget)
  Don't pass the internal widget wrapper out - instead, build the entire widget tree from the config internally.

### Phasing out for 2.0
- [ ] `src/valueObjects/Cursor` (`CURSOR_COMPATIBILITY_SYMBOL` only)

### Hardcode variable values ¯\_(ツ)_/¯
- [ ] css var/apply
</details>
