### ISSUE TITLE
Docs: add known issues and solutions section to the docs

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-cms#3827]
Related to https://github.com/netlify/netlify-cms/issues/2827

We should add a "known issues" section to the docs so users can self serve common issues.
Partial list to be updated:
- [ ] GitHub private+public+organisations permissions issues (e.g. https://github.com/netlify/netlify-cms/issues/1415)
- [ ] Having a branch named `cms` fails editorial workflow (https://github.com/netlify/netlify-cms/issues/3065)
- [ ] Working with multiple CMS instances/environments (e.g https://github.com/netlify/netlify-cms/issues/3790)
- [ ] Git gateway + Identity issues (e.g. https://github.com/netlify/netlify-cms/issues/3718 and https://community.netlify.com/t/common-issue-netlify-cms-git-gateway-email-not-confirmed/10690)

Please add more in the comments if you have them

**Comment by lilpolymath** [comment]
I will work on this. If there are other issues commonly faced, I will check around too.

**Comment by ylc-website** [comment]
I'm not sure what to do with `Failed to persist entry: API_ERROR: Operator microservice headers missing category:48`
